### ISSUE TITLE
BC6H_UF16 dds file import

### ISSUE THREAD

**Issue by djewsbury** [inalogic/pico-pixel-client-sdk#1]
Hi,

Just wanted to drop a line and say -- fantastic app! I've been trying the client as a quick image preview app, and it's just fantastic. Support for HDR cubemaps in DDS is really handy.

I haven't used the pixel-printf stuff yet; but I do a lot of graphics programming so that quick preview sounds great for debugging stuff. In the past I've used hacked-up solutions to do the same thing, but Pico Pixel seems much better.

I'm getting some problems with BC6H_UF16 dds files. I'll attach a small cubemap that gets different results in other applications. This was compressed with the DirectXTex library from Microsoft.

I'm using 0.6.8 off the main "http://pixelandpolygon.com/" page.

[brick_lounge_2k_diffuse.zip](https://github.com/inalogic/pico-pixel-client-sdk/files/111121/brick_lounge_2k_diffuse.zip)

**Comment by jaytaoko** [comment]
Thank you for your feedback.
Pico Pixel has been on pause for a little while but development will resume soon.
I will start by looking into the texture format issue you reported.

Regards
Jay

**Comment by djewsbury** [comment]
Great, thanks. 
On further inspection, I've found that the problem may be related to the BC6H_UF16 format specifically. The BC6H_SF16 format seems to work fine.

I'm also having problems with 16 bit UNORM formats -- eg R16G16_UNORM. These may be interpreted as integer values, but they should be normalized values between 0 and 1.

Obviously these are unusual formats. But this is where pico pixel could be most useful to me; because it's hard to find good tools that support them.

**Comment by jaytaoko** [comment]
This is the result after the fix. A PicoPixel release will follow soon. 

![bc6h_uf16-fix](https://cloud.githubusercontent.com/assets/1514772/13275129/c1704b64-da7f-11e5-8753-a3c1ea6eee17.png)

Fell free to post image files that you think aren't rendered correctly in PicoPixel.
Regards!

**Comment by jaytaoko** [comment]
The fix for this issue has been released in PicoPixel 0.6.9.
Thank you for reporting.
